name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-14, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Set up corepack
        run: corepack enable yarn

      - name: Cache Dirs
        uses: actions/cache@v6
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Update Ruffle
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ruffle/download-latest-ruffle.sh
        shell: bash

      - name: Run Build
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          PLATFORM: ${{ matrix.platform }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        shell: bash

        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ] || [ -f ./force_release ]; then
            export BUILD_CMD="release"
          else
            export BUILD_CMD="dist"
          fi

          yarn install --immutable
          yarn run $BUILD_CMD
