name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up corepack
        run: corepack enable yarn

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Yarn Install
        run: yarn install --immutable

      - name: Yarn Run Build
        run: yarn run build

      - name: Npm Publish Pre-Release!
        if: github.event.release.prerelease
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Npm Publish!
        if: ${{ !github.event.release.prerelease }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
