name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Yarn Run Build
        run: yarn run build

      - name: Npm Publish!
        run: npm publish
